- name: create mjob.xml file
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/mjob.xml') }}"
    name: mjob.xml
    password: admin123
    url: http://172.31.44.131:8080
    user: admin


- name: copy mjob.xml file
  ansible.builtin.template:
    src: mjob.xml
    dest: /tmp/test.xml
    #when: jenkins_job_status.failed or override

- name: Create Jenkins Jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/test.xml') }}"
    name: "{{item.job_name}}"
    password: admin123
    url: http://172.31.44.131:8080
    user: admin
    # when: jenkins_job_status.failed or override