- name: sjobs Create .xml file
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/mjobs.xml') }}"
    name: sjob.xml
    password: admin123
    url: http://172.31.44.131:8080
    user: admin


- name: copy sjob.xml file
  ansible.builtin.template:
    name: mjobs.xml
    dest: /var/lib/jenkins

- name: sjobs Create .xml file
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/mjobs.xml') }}"
    name: sjob.xml
    password: admin123
    url: http://172.31.44.131:8080
    user: admin